### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by BillDietrich** [CrazyPython/wwwpreiodictable#1]
Great idea !  A couple of suggestions:

- scale the page so it doesn't scroll horizontally.  Maybe:
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    body style="max-width:100%;"
or something like that.

- the symbols just distract when there already is a well-known acronym.  For example, adding "Mail" above "SMTP", or "Hx" above "XHTML", just seems to make clutter.

**Comment by CrazyPython** [comment]
> the symbols just distract when there already is a well-known acronym. For example, adding "Mail" above "SMTP", or "Hx" above "XHTML", just seems to make clutter.

Fixed in 00096f5

**Comment by CrazyPython** [comment]
> the symbols just distract when there already is a well-known acronym. For example, adding "Mail" above "SMTP", or "Hx" above "XHTML", just seems to make clutter.

Fixed in 00096f5
