### ISSUE TITLE
Make font size somewhat bigger for mobile phones

### ISSUE THREAD

**Issue by CrazyPython** [CrazyPython/wwwpreiodictable#21]
It looks like this on mobile:

![image](https://user-images.githubusercontent.com/2363105/105501283-02fc4580-5c92-11eb-89ac-b608d44ede9b.png)

@codestance I'm unsure of how to proceed to fix this responsiveness issue, can you help?

**Comment by codestance** [comment]
To do this, the cell width must be increased.

**Comment by codestance** [comment]
Oh, I know what happend. Viewport is not set.
