### ISSUE TITLE
Fix layout on mobile

### ISSUE THREAD

**Issue by CrazyPython** [CrazyPython/wwwpreiodictable#6]
Options
 * Try fixing it as it exists
 * Replace it with CSS Grid

**Comment by KshitizDayal** [comment]
Hi there!
Nice idea. I just wanted to tell that if you can add css to the code then it will be much better looking.
And also I am interested in working on this project. Please let me know what I can do .

**Comment by CrazyPython** [comment]
Yes, you can help this project. Feel free to send me a pull request with relevant changes after you write code. Also, feel free to discuss the project in issues.

**Comment by CrazyPython** [comment]
Before:
![Google Search Console. Google Index tab. Page is not mobile friendly; Text too small to read, Clickable elements too close together, Viewport not set](https://user-images.githubusercontent.com/2363105/105501376-20311400-5c92-11eb-83fa-d781a753b05e.png)

After:
![Google Search Console. Live test tab. Page is mobile friendly; crawled successfully](https://user-images.githubusercontent.com/2363105/105501445-3a6af200-5c92-11eb-8356-e87d08e689cc.png)

Thanks!
